Improvements for making this testsuite compatible with EAP 7.1
richfaces/richfaces-qa pull request #19
Opened 2016-09-29 14:05 UTC by honza-kasik

* Updated Arquillian dependencies
* Removed conflicting Guava dependencies and replaced it by one artifact (19.0)
* Removed `org.jboss.logging` dependencies and replaced it by one artifact (3.3.0.Final)
* Added `org.jboss.logging` to `MANIFEST.MF` as dependency
* Added Creaper where required

2016-09-29 14:20 UTC, rhatlapa reviewed
Comments for improvements, none of them blocks this PR.

In general it LGTM, I just don't like very much usage of the `System.exit` If there is good reason for it, it is good to be merged from my PoV.

2016-09-29 14:20 UTC, rhatlapa commented on metamer/ftest/src/test/java/org/richfaces/tests/metamer/ftest/utils/ManagementClientProvider.java
> +}
Missing EOF

2016-09-29 14:20 UTC, rhatlapa commented on metamer/ftest/src/test/java/org/richfaces/tests/metamer/ftest/extension/arquillian/JBossPatchInstaller.java
>                  System.exit(1);
Originally there was also called `System.exit` when `applyPatch` failed, we should either in both cases throw exception or do `System.exit`

NOTE, I've noticed that `applyPatch` actually does also System.exit, so there is no inconsistency. Still I would prefer rather having thrown exception. Exception is more informative than exit code.

2016-09-29 14:20 UTC, rhatlapa commented on metamer/ftest/src/test/java/org/richfaces/tests/metamer/ftest/extension/arquillian/JBossPatchInstaller.java
> +    private void applyPatch(String pathToPatch) {
Why there is used `System.exit`? Wouldn't it make sense to throw exception? System.exit called in different method than main method doesn't seem right.

2016-09-29 14:26 UTC, honza-kasik commented
Please do not merge - needs testing for patching due to rewriting its code, both online and offline mode..

2016-09-30 11:25 UTC, ppitonak commented on metamer/application/pom.xml
> +            <version>3.3.0.Final</version>
Shouldn't this dependency be in scope "provided" when it's listed it manifest.mf?

2016-09-30 11:25 UTC, ppitonak commented on pom.xml
> +                                <JBOSS_HOME>${jbossEAP70Home}</JBOSS_HOME>
I would either rename `jbossEAP70Home` to `jbossEAP7Home` and used it for both 7.0 and 7.1 or created a new property specific for EAP 7.1.

2016-09-30 11:27 UTC, ppitonak commented
@honza-kasik common practice is to prefix PR title with "WIP" if you don't want it to be merged.

2016-10-03 10:02 UTC, honza-kasik commented
I worked in suggestions from comments and tested patching, which now works correctly

2016-10-04 08:13 UTC, rhatlapa requested changes
Just minor things, see above.

PS: still there wasn't answered question for doing System.exit instead of throwing exception.

2016-10-04 08:13 UTC, rhatlapa commented on metamer/ftest/src/test/java/org/richfaces/tests/metamer/ftest/extension/arquillian/creaper/ApplyPatch.java
> +    public void apply(OfflineCommandContext ctx) throws Exception {
Put the method before the inner class.

2016-10-04 08:13 UTC, rhatlapa commented on metamer/ftest/src/test/java/org/richfaces/tests/metamer/ftest/utils/ManagementClientProvider.java
> +                .build());
What about older JBoss AS7 (EAP 6)? Is there used different branch for its testing?

2016-10-06 09:12 UTC, honza-kasik commented on metamer/ftest/src/test/java/org/richfaces/tests/metamer/ftest/extension/arquillian/JBossPatchInstaller.java
>                  System.exit(1);
I tried to remove System#exit() and use exceptions instead. But thrown exception wont stop tests from running (each of them starts and then it is skipped immediately). I think that the System#exit() is there to stop starting of tests...

2016-10-06 09:46 UTC, honza-kasik commented on metamer/ftest/src/test/java/org/richfaces/tests/metamer/ftest/utils/ManagementClientProvider.java
> +                .build());
No there is not used another branch. This is my mistake since I forgot, the management ports are different... I try to come up with a solution.

2016-10-17 11:49 UTC, honza-kasik commented on metamer/ftest/src/test/java/org/richfaces/tests/metamer/ftest/utils/ManagementClientProvider.java
> +                .build());
Created branch eap-64x for EAP 6.4.z

2016-10-21 13:35 UTC, honza-kasik commented
It looks like it is ready to be merged. Hopefully, I finally solved all the issues.

2016-10-25 19:56 UTC, rhatlapa approved these changes
LGTM, just rather minor comments.

2016-10-25 19:56 UTC, rhatlapa commented on metamer/ftest/src/test/java/org/richfaces/tests/metamer/ftest/AbstractMetamerTest.java
> +            if (client != null) {
client is never null, no need to check for not null value.

2016-10-25 19:56 UTC, rhatlapa commented on metamer/ftest/src/test/java/org/richfaces/tests/metamer/ftest/AbstractMetamerTest.java
> +            if (client != null) {
client is never null at this part of code, no need to check for not null value.

2016-10-25 19:56 UTC, rhatlapa commented on metamer/ftest/src/test/java/org/richfaces/tests/metamer/ftest/extension/creaper/ApplyPatch.java
> +        executeCliOffline(cmd.toString(), ctx);
It is better to reuse the cmd command creation which is completely the same as for online command.

2016-10-25 19:56 UTC, rhatlapa commented on metamer/ftest/src/test/java/org/richfaces/tests/metamer/ftest/extension/creaper/PatchingConversions.java
> +final class PatchingConversions {
Missing javadoc explaining what the class is used for.

2016-10-25 19:56 UTC, rhatlapa commented on metamer/ftest/src/test/java/org/richfaces/tests/metamer/ftest/utils/ManagementClientProvider.java
> +                .build());
EAP/WildFly version can be easily found out from offline client if needed. If this is the only reason for separating the branches than we should reconsider. If there are some other issues such as with dependencies, then OK.

2016-10-27 12:22 UTC, honza-kasik commented
All suggestion worked in, thanks! For EAP 6.4, there is a problem with dependencies, which solving seems time-consuming...

2016-10-27 12:33 UTC, rhatlapa commented
Thanks, LGTM, please squash and I shall merge.

2016-10-27 12:40 UTC, honza-kasik commented
Squashed and ready to be merged, thanks!

2016-10-27 12:52 UTC, rhatlapa commented
Thanks, merging.

2016-10-27 12:52 UTC, merged